#!/bin/bash
cd /home/pi/pits-camera/camera
sudo modprobe w1-gpio
sudo modprobe w1_therm
sudo modprobe i2c-dev
echo none | sudo tee /sys/class/leds/led0/trigger
echo 1 | sudo tee /sys/class/leds/led0/brightness
# sudo ./camera &
#python3 sensors.py &
#python3 astro_led.py &
#python3 webstuff.py
# sudo ./camera
while :
do
	sudo ./camera
	sleep 5
done
