#! /bin/sh
# /etc/init.d/camera
#

# Some things that run always
touch /var/lock/camera

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script camera "
    /home/pi/pits-camera/camera/startup &
    ;;
  stop)
    echo "Stopping script camera"
    ;;
  *)
    echo "Usage: /etc/init.d/camera {start|stop}"
    exit 1
    ;;
esac

exit 0
